### ISSUE TITLE
I'm getting errors and command not found

### ISSUE THREAD

**Issue by SolarAquarion** [LarsEKrueger/bite#2]

**Comment by LarsEKrueger** [comment]
Please add the error message to this thread

**Comment by SolarAquarion** [comment]
bite: complete: command not found
bite: bind: command not found
bite: about ...
bite: example ......

**Comment by LarsEKrueger** [comment]
This might an artifact of the not-yet-complete integration of bash. bite should work despite the messages.

I will update the readme file to state so.

Edit: These messages seem to stem from your .bashrc / .profile / .bash_profile file as those I get are different. complete and bind are quite common in those scripts, but should be found as they are built-in commands and I have those in my scripts as well.

Do you see these message inside the bite window or in the terminal window from which you started bite?

Do you see these message at every start or when you type them manually?

Esp. the about and example lines should be easy to find in the start scripts. If you could post the offending lines and which files they are from, I can try to replicate this on my machine.

**Comment by LarsEKrueger** [comment]
No response for a week. I assume the updated documentation was sufficient. I will close the issue.
